### ISSUE TITLE
Error during installation process

### ISSUE THREAD

**Issue by farshadf** [Yandell-Lab/taxonomer_0.5#10]
Hi,

I am trying to install the latest taxonomer (taxonomer_0.5), and unfortunately there is not much progress due to a problem I cannot understand. This is the error message :
> python setup.py build_ext --inplace
Compiling scripts/cython/binner_PY.pyx because it changed.
Compiling scripts/cython/build_DBpy.pyx because it changed.
Compiling scripts/cython/classify_READpy.pyx because it changed.
Compiling scripts/cython/binner_splitpy.pyx because it changed.
Compiling scripts/cython/binner_mergepy.pyx because it changed.
[1/5] Cythonizing scripts/cython/binner_PY.pyx

Error compiling Cython file:
------------------------------------------------------------
...
cimport binnerPY
^
------------------------------------------------------------

scripts/cython/binner_PY.pyx:1:0: 'scripts/cython/binner_PY' is not a valid module name
Traceback (most recent call last):
  File "setup.py", line 17, in <module>
    Extension("scripts/cython/binner_mergepy",sources=["scripts/cython/binner_mergepy.pyx"])
  File ".../miniconda3/lib/python3.7/site-packages/Cython/Build/Dependencies.py", line 1096, in cythonize
    cythonize_one(*args)
  File ".../miniconda3/lib/python3.7/site-packages/Cython/Build/Dependencies.py", line 1219, in cythonize_one
    raise CompileError(None, pyx_file)
Cython.Compiler.Errors.CompileError: scripts/cython/binner_PY.pyx

I am using python 3.7 and cython is installed through conda and can be readily found on the PATH. The package is copied by git. Can you please help me to rectify this problem?

**Comment by MaHaoran627** [comment]
Same issue. Python2.7, Cython and biopython were built via conda.

**Comment by stevendflygare** [comment]
The dependency requirements were too vague which is causing the issues you are experiencing (readme has now been updated to reflect this).  Python version must be 2.7, cython version must be 0.20.1.  I just complied the code on a linux machine that has these package versions and everything built okay.  The REAME.md has been updated to reflect these requirements.  Something to keep in mind is this tool is several years old and has never been updated, nor will it be.
